# Generated by Django 5.0.3 on 2024-05-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=56)),
                ('flag', models.ImageField(upload_to='flags/')),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_languages', to='learn.flag'),
        ),
    ]
