# Generated by Django 5.0.3 on 2024-05-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolled_users', models.ManyToManyField(related_name='enrolled_coursers', to=settings.AUTH_USER_MODEL)),
                ('origin_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_language_in', to='learn.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language_in', to='learn.language')),
            ],
        ),
    ]
