# Generated by Django 5.0.3 on 2024-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_remove_course_active_users_lesson_completed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='lesson',
        ),
        migrations.AddField(
            model_name='translation',
            name='lesson',
            field=models.ManyToManyField(related_name='words', to='learn.lesson'),
        ),
    ]
