# Generated by Django 5.0.3 on 2024-05-26 19:01

import django.db.models.deletion
import learn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_course_enrolled_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=35)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('number_in_course', models.PositiveIntegerField(default=learn.models.Section.get_default_number_in_course)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learn.course')),
            ],
        ),
    ]
