# Generated by Django 5.0.3 on 2024-05-28 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_translation_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='translation',
            name='seen_by',
            field=models.ManyToManyField(db_index=True, related_name='seen_translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
