# Generated by Django 5.0.3 on 2024-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number_in_course',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
