# Generated by Django 5.0.3 on 2024-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_remove_word_seen_by_translation_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='granted_xp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='session',
            name='earned_xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
