# Generated by Django 5.0.3 on 2024-05-31 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_alter_course_enrolled_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='completed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
