# Generated by Django 5.0.3 on 2024-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_alter_lesson_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('final', 'final')], default='normal', max_length=6),
        ),
    ]
