# Generated by Django 5.0.3 on 2024-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='variant',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary'), ('yellow', 'yellow'), ('red', 'red'), ('indigo', 'indigo')], default='primary', max_length=10),
        ),
    ]
