# Generated by Django 5.0.3 on 2024-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_section_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='sound',
            field=models.TextField(blank=True, null=True),
        ),
    ]
